See also Throwing and Catching Exceptions. The try-catch blocks are used to catch any exceptions or other throwable objects within the code. Here's what try-catch blocks looks like: try {statement1.1statement1.2...statement1.n} catch (exception1) {statement2.1...statement2.n} The code listing 3.6 tries to print all the arguments that have been passed to the program. However, if there not enough arguments, it will throw an exception. Code listing 3.6: Attempt.java 1 public class Attempt { 2   public static void main(String[] args) { 3     try { 4       System.out.println(args[0]); 5       System.out.println(args[1]); 6       System.out.println(args[2]); 7       System.out.println(args[3]); 8     } catch (ArrayIndexOutOfBoundsException e) { 9       System.out.println("Not enough arguments");10     }11   }12 } In addition to the try and catch blocks, a finally block may be present. The finally block is always executed, even if an exception is thrown. It may appear with or without a catch block, but always with a try block. Here is what a finally block looks like: try {statement1.1statement1.2...statement1.n} catch (exception1) {statement2.1...statement2.n} finally {statement3.1...statement3.n}